if(NOT DEFINED CLI OR NOT DEFINED SOURCE OR NOT DEFINED DATABASE OR NOT DEFINED COMMANDS)
    message(FATAL_ERROR "Missing acceptance paths")
endif()
file(SHA256 "${SOURCE}/main.cpp" before)
foreach(command scan symbols metrics call include status)
    if(command STREQUAL "scan")
        set(args scan "${SOURCE}" --database "${DATABASE}" --compile-commands "${COMMANDS}")
    elseif(command STREQUAL "call" OR command STREQUAL "include")
        set(args graph "${SOURCE}" --database "${DATABASE}" --kind "${command}")
    else()
        set(args "${command}" "${SOURCE}" --database "${DATABASE}")
    endif()
    execute_process(COMMAND "${CLI}" ${args} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    if(NOT status EQUAL 0 OR NOT output MATCHES "analysis=complete")
        message(FATAL_ERROR "${command} failed (${status}): ${output}\n${errors}")
    endif()
    if((command STREQUAL "call" OR command STREQUAL "include") AND NOT output MATCHES "cyclic_components=1")
        message(FATAL_ERROR "${command}: expected exactly one cyclic SCC: ${output}")
    endif()
    file(WRITE "${DATABASE}.${command}.txt" "${output}\n${errors}")
endforeach()
file(SHA256 "${DATABASE}" db_before)
execute_process(COMMAND "${CLI}" query "${SOURCE}" --database "${DATABASE}"
    --query "SELECT name, complexity FROM functions WHERE complexity >= 1 ORDER BY complexity DESC LIMIT 2"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
if(NOT status EQUAL 0 OR NOT output MATCHES "name\tcomplexity" OR NOT errors MATCHES "StableSort")
    message(FATAL_ERROR "query failed (${status}): ${output}\n${errors}")
endif()
execute_process(COMMAND "${CLI}" query "${SOURCE}" --database "${DATABASE}"
    --query "SELECT * FROM functions WHERE complexity = 'bad'"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
if(NOT status EQUAL 1 OR NOT errors MATCHES "type mismatch")
    message(FATAL_ERROR "invalid query accepted: ${status} ${output} ${errors}")
endif()
file(SHA256 "${DATABASE}" db_after)
if(NOT db_before STREQUAL db_after)
    message(FATAL_ERROR "Queries modified the database")
endif()
file(SHA256 "${SOURCE}/main.cpp" after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Source changed")
endif()
message(STATUS "CLI_ANALYSIS_OK: persisted symbols/metrics/graphs and immutable source")
