foreach(file main.cpp quality.cpp CMakeLists.txt)
    file(SHA256 "${SOURCE}/${file}" "before_${file}")
endforeach()
execute_process(COMMAND "${CLI}" scan "${SOURCE}" --database "${DATABASE}" --compile-commands "${COMMANDS}" --threads 2
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
if(NOT result EQUAL 0 OR NOT output MATCHES "issues=5")
    message(FATAL_ERROR "CLI rules scan failed: ${output} ${error}")
endif()
execute_process(COMMAND "${CLI}" issues "${SOURCE}" --database "${DATABASE}" --severity error
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
if(NOT result EQUAL 0 OR NOT output MATCHES "CG002" OR output MATCHES "CG001")
    message(FATAL_ERROR "CLI issue filtering failed: ${output} ${error}")
endif()
execute_process(COMMAND "${CLI}" build "${SOURCE}" --database "${DATABASE}" --output "${OUTPUT}" --jobs 2 --timeout 30
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 60)
if(NOT result EQUAL 0 OR NOT output MATCHES "status=passed" OR NOT output MATCHES "tests=1 failed=0 skipped=0")
    message(FATAL_ERROR "CLI build/test failed: ${output} ${error}")
endif()
execute_process(COMMAND "${CLI}" query "${SOURCE}" --database "${DATABASE}" --query "SELECT stage, tests_total FROM builds WHERE stage = 'test' ORDER BY run_id DESC LIMIT 1"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
if(NOT result EQUAL 0 OR NOT output MATCHES "test\t1")
    message(FATAL_ERROR "CLI build query failed: ${output} ${error}")
endif()
foreach(file main.cpp quality.cpp CMakeLists.txt)
    file(SHA256 "${SOURCE}/${file}" after)
    if(NOT after STREQUAL "${before_${file}}")
        message(FATAL_ERROR "Source changed: ${file}")
    endif()
endforeach()
message(STATUS "LEVEL3_CLI_OK")
